package com.hqjcloud.provider.domain;

public class AaTrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.orderid
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.tradetime
     *
     * @mbg.generated
     */
    private Long tradetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.masterid
     *
     * @mbg.generated
     */
    private Long masterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.masterrealname
     *
     * @mbg.generated
     */
    private String masterrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.sellerid
     *
     * @mbg.generated
     */
    private Long sellerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.sellerrealname
     *
     * @mbg.generated
     */
    private String sellerrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.ZH
     *
     * @mbg.generated
     */
    private Double zh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.tradetype
     *
     * @mbg.generated
     */
    private String tradetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.paypeo
     *
     * @mbg.generated
     */
    private Integer paypeo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_aa_trade.flag
     *
     * @mbg.generated
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.longid
     *
     * @return the value of hqj_aa_trade.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.longid
     *
     * @param longid the value for hqj_aa_trade.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.orderid
     *
     * @return the value of hqj_aa_trade.orderid
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.orderid
     *
     * @param orderid the value for hqj_aa_trade.orderid
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.tradetime
     *
     * @return the value of hqj_aa_trade.tradetime
     *
     * @mbg.generated
     */
    public Long getTradetime() {
        return tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.tradetime
     *
     * @param tradetime the value for hqj_aa_trade.tradetime
     *
     * @mbg.generated
     */
    public void setTradetime(Long tradetime) {
        this.tradetime = tradetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.masterid
     *
     * @return the value of hqj_aa_trade.masterid
     *
     * @mbg.generated
     */
    public Long getMasterid() {
        return masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.masterid
     *
     * @param masterid the value for hqj_aa_trade.masterid
     *
     * @mbg.generated
     */
    public void setMasterid(Long masterid) {
        this.masterid = masterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.masterrealname
     *
     * @return the value of hqj_aa_trade.masterrealname
     *
     * @mbg.generated
     */
    public String getMasterrealname() {
        return masterrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.masterrealname
     *
     * @param masterrealname the value for hqj_aa_trade.masterrealname
     *
     * @mbg.generated
     */
    public void setMasterrealname(String masterrealname) {
        this.masterrealname = masterrealname == null ? null : masterrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.sellerid
     *
     * @return the value of hqj_aa_trade.sellerid
     *
     * @mbg.generated
     */
    public Long getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.sellerid
     *
     * @param sellerid the value for hqj_aa_trade.sellerid
     *
     * @mbg.generated
     */
    public void setSellerid(Long sellerid) {
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.sellerrealname
     *
     * @return the value of hqj_aa_trade.sellerrealname
     *
     * @mbg.generated
     */
    public String getSellerrealname() {
        return sellerrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.sellerrealname
     *
     * @param sellerrealname the value for hqj_aa_trade.sellerrealname
     *
     * @mbg.generated
     */
    public void setSellerrealname(String sellerrealname) {
        this.sellerrealname = sellerrealname == null ? null : sellerrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.currency
     *
     * @return the value of hqj_aa_trade.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.currency
     *
     * @param currency the value for hqj_aa_trade.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.amount
     *
     * @return the value of hqj_aa_trade.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.amount
     *
     * @param amount the value for hqj_aa_trade.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.ZH
     *
     * @return the value of hqj_aa_trade.ZH
     *
     * @mbg.generated
     */
    public Double getZh() {
        return zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.ZH
     *
     * @param zh the value for hqj_aa_trade.ZH
     *
     * @mbg.generated
     */
    public void setZh(Double zh) {
        this.zh = zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.tradetype
     *
     * @return the value of hqj_aa_trade.tradetype
     *
     * @mbg.generated
     */
    public String getTradetype() {
        return tradetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.tradetype
     *
     * @param tradetype the value for hqj_aa_trade.tradetype
     *
     * @mbg.generated
     */
    public void setTradetype(String tradetype) {
        this.tradetype = tradetype == null ? null : tradetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.comment
     *
     * @return the value of hqj_aa_trade.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.comment
     *
     * @param comment the value for hqj_aa_trade.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.paypeo
     *
     * @return the value of hqj_aa_trade.paypeo
     *
     * @mbg.generated
     */
    public Integer getPaypeo() {
        return paypeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.paypeo
     *
     * @param paypeo the value for hqj_aa_trade.paypeo
     *
     * @mbg.generated
     */
    public void setPaypeo(Integer paypeo) {
        this.paypeo = paypeo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_aa_trade.flag
     *
     * @return the value of hqj_aa_trade.flag
     *
     * @mbg.generated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_aa_trade.flag
     *
     * @param flag the value for hqj_aa_trade.flag
     *
     * @mbg.generated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}