package com.hqjcloud.article.beans;

public class ArticleClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclass.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclass.classname
     *
     * @mbg.generated
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclass.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclass.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclass.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclass.longid
     *
     * @return the value of hqj_articleclass.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclass.longid
     *
     * @param longid the value for hqj_articleclass.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclass.classname
     *
     * @return the value of hqj_articleclass.classname
     *
     * @mbg.generated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclass.classname
     *
     * @param classname the value for hqj_articleclass.classname
     *
     * @mbg.generated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclass.addtime
     *
     * @return the value of hqj_articleclass.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclass.addtime
     *
     * @param addtime the value for hqj_articleclass.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclass.sort
     *
     * @return the value of hqj_articleclass.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclass.sort
     *
     * @param sort the value for hqj_articleclass.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclass.status
     *
     * @return the value of hqj_articleclass.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclass.status
     *
     * @param status the value for hqj_articleclass.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}