package com.hqjcloud.article.beans;

public class ArticleClassRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclassrelation.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclassrelation.articleId
     *
     * @mbg.generated
     */
    private Long articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclassrelation.articleclassid
     *
     * @mbg.generated
     */
    private Long articleclassid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articleclassrelation.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclassrelation.longid
     *
     * @return the value of hqj_articleclassrelation.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclassrelation.longid
     *
     * @param longid the value for hqj_articleclassrelation.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclassrelation.articleId
     *
     * @return the value of hqj_articleclassrelation.articleId
     *
     * @mbg.generated
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclassrelation.articleId
     *
     * @param articleid the value for hqj_articleclassrelation.articleId
     *
     * @mbg.generated
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclassrelation.articleclassid
     *
     * @return the value of hqj_articleclassrelation.articleclassid
     *
     * @mbg.generated
     */
    public Long getArticleclassid() {
        return articleclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclassrelation.articleclassid
     *
     * @param articleclassid the value for hqj_articleclassrelation.articleclassid
     *
     * @mbg.generated
     */
    public void setArticleclassid(Long articleclassid) {
        this.articleclassid = articleclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articleclassrelation.addtime
     *
     * @return the value of hqj_articleclassrelation.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articleclassrelation.addtime
     *
     * @param addtime the value for hqj_articleclassrelation.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }
}