package com.hqjcloud.article.beans;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.arttitle
     *
     * @mbg.generated
     */
    private String arttitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.artabstract
     *
     * @mbg.generated
     */
    private String artabstract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.artimage
     *
     * @mbg.generated
     */
    private String artimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.visitcnt
     *
     * @mbg.generated
     */
    private Long visitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.artstatus
     *
     * @mbg.generated
     */
    private Integer artstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.likes
     *
     * @mbg.generated
     */
    private Long likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.addauthor
     *
     * @mbg.generated
     */
    private String addauthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.artSort
     *
     * @mbg.generated
     */
    private Integer artsort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.istop
     *
     * @mbg.generated
     */
    private Byte istop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.modifytime
     *
     * @mbg.generated
     */
    private Long modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.pubtime
     *
     * @mbg.generated
     */
    private Long pubtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.artcontent
     *
     * @mbg.generated
     */
    private String artcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.longid
     *
     * @return the value of hqj_article.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.longid
     *
     * @param longid the value for hqj_article.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.arttitle
     *
     * @return the value of hqj_article.arttitle
     *
     * @mbg.generated
     */
    public String getArttitle() {
        return arttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.arttitle
     *
     * @param arttitle the value for hqj_article.arttitle
     *
     * @mbg.generated
     */
    public void setArttitle(String arttitle) {
        this.arttitle = arttitle == null ? null : arttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.artabstract
     *
     * @return the value of hqj_article.artabstract
     *
     * @mbg.generated
     */
    public String getArtabstract() {
        return artabstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.artabstract
     *
     * @param artabstract the value for hqj_article.artabstract
     *
     * @mbg.generated
     */
    public void setArtabstract(String artabstract) {
        this.artabstract = artabstract == null ? null : artabstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.artimage
     *
     * @return the value of hqj_article.artimage
     *
     * @mbg.generated
     */
    public String getArtimage() {
        return artimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.artimage
     *
     * @param artimage the value for hqj_article.artimage
     *
     * @mbg.generated
     */
    public void setArtimage(String artimage) {
        this.artimage = artimage == null ? null : artimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.visitcnt
     *
     * @return the value of hqj_article.visitcnt
     *
     * @mbg.generated
     */
    public Long getVisitcnt() {
        return visitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.visitcnt
     *
     * @param visitcnt the value for hqj_article.visitcnt
     *
     * @mbg.generated
     */
    public void setVisitcnt(Long visitcnt) {
        this.visitcnt = visitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.artstatus
     *
     * @return the value of hqj_article.artstatus
     *
     * @mbg.generated
     */
    public Integer getArtstatus() {
        return artstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.artstatus
     *
     * @param artstatus the value for hqj_article.artstatus
     *
     * @mbg.generated
     */
    public void setArtstatus(Integer artstatus) {
        this.artstatus = artstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.likes
     *
     * @return the value of hqj_article.likes
     *
     * @mbg.generated
     */
    public Long getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.likes
     *
     * @param likes the value for hqj_article.likes
     *
     * @mbg.generated
     */
    public void setLikes(Long likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.addauthor
     *
     * @return the value of hqj_article.addauthor
     *
     * @mbg.generated
     */
    public String getAddauthor() {
        return addauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.addauthor
     *
     * @param addauthor the value for hqj_article.addauthor
     *
     * @mbg.generated
     */
    public void setAddauthor(String addauthor) {
        this.addauthor = addauthor == null ? null : addauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.artSort
     *
     * @return the value of hqj_article.artSort
     *
     * @mbg.generated
     */
    public Integer getArtsort() {
        return artsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.artSort
     *
     * @param artsort the value for hqj_article.artSort
     *
     * @mbg.generated
     */
    public void setArtsort(Integer artsort) {
        this.artsort = artsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.istop
     *
     * @return the value of hqj_article.istop
     *
     * @mbg.generated
     */
    public Byte getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.istop
     *
     * @param istop the value for hqj_article.istop
     *
     * @mbg.generated
     */
    public void setIstop(Byte istop) {
        this.istop = istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.addtime
     *
     * @return the value of hqj_article.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.addtime
     *
     * @param addtime the value for hqj_article.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.modifytime
     *
     * @return the value of hqj_article.modifytime
     *
     * @mbg.generated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.modifytime
     *
     * @param modifytime the value for hqj_article.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.pubtime
     *
     * @return the value of hqj_article.pubtime
     *
     * @mbg.generated
     */
    public Long getPubtime() {
        return pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.pubtime
     *
     * @param pubtime the value for hqj_article.pubtime
     *
     * @mbg.generated
     */
    public void setPubtime(Long pubtime) {
        this.pubtime = pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.artcontent
     *
     * @return the value of hqj_article.artcontent
     *
     * @mbg.generated
     */
    public String getArtcontent() {
        return artcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.artcontent
     *
     * @param artcontent the value for hqj_article.artcontent
     *
     * @mbg.generated
     */
    public void setArtcontent(String artcontent) {
        this.artcontent = artcontent == null ? null : artcontent.trim();
    }
}