package com.hqjcloud.article.beans;

public class ArticleTagRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articletagrelation.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articletagrelation.tagid
     *
     * @mbg.generated
     */
    private Long tagid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articletagrelation.articleid
     *
     * @mbg.generated
     */
    private Long articleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_articletagrelation.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articletagrelation.longid
     *
     * @return the value of hqj_articletagrelation.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articletagrelation.longid
     *
     * @param longid the value for hqj_articletagrelation.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articletagrelation.tagid
     *
     * @return the value of hqj_articletagrelation.tagid
     *
     * @mbg.generated
     */
    public Long getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articletagrelation.tagid
     *
     * @param tagid the value for hqj_articletagrelation.tagid
     *
     * @mbg.generated
     */
    public void setTagid(Long tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articletagrelation.articleid
     *
     * @return the value of hqj_articletagrelation.articleid
     *
     * @mbg.generated
     */
    public Long getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articletagrelation.articleid
     *
     * @param articleid the value for hqj_articletagrelation.articleid
     *
     * @mbg.generated
     */
    public void setArticleid(Long articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_articletagrelation.addtime
     *
     * @return the value of hqj_articletagrelation.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_articletagrelation.addtime
     *
     * @param addtime the value for hqj_articletagrelation.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }
}