package com.hqjcloud.article.beans;

import java.util.ArrayList;
import java.util.List;

public class ArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public ArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLongidIsNull() {
            addCriterion("longid is null");
            return (Criteria) this;
        }

        public Criteria andLongidIsNotNull() {
            addCriterion("longid is not null");
            return (Criteria) this;
        }

        public Criteria andLongidEqualTo(Long value) {
            addCriterion("longid =", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotEqualTo(Long value) {
            addCriterion("longid <>", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidGreaterThan(Long value) {
            addCriterion("longid >", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidGreaterThanOrEqualTo(Long value) {
            addCriterion("longid >=", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidLessThan(Long value) {
            addCriterion("longid <", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidLessThanOrEqualTo(Long value) {
            addCriterion("longid <=", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidIn(List<Long> values) {
            addCriterion("longid in", values, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotIn(List<Long> values) {
            addCriterion("longid not in", values, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidBetween(Long value1, Long value2) {
            addCriterion("longid between", value1, value2, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotBetween(Long value1, Long value2) {
            addCriterion("longid not between", value1, value2, "longid");
            return (Criteria) this;
        }

        public Criteria andArtTitleIsNull() {
            addCriterion("art_title is null");
            return (Criteria) this;
        }

        public Criteria andArtTitleIsNotNull() {
            addCriterion("art_title is not null");
            return (Criteria) this;
        }

        public Criteria andArtTitleEqualTo(String value) {
            addCriterion("art_title =", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleNotEqualTo(String value) {
            addCriterion("art_title <>", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleGreaterThan(String value) {
            addCriterion("art_title >", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleGreaterThanOrEqualTo(String value) {
            addCriterion("art_title >=", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleLessThan(String value) {
            addCriterion("art_title <", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleLessThanOrEqualTo(String value) {
            addCriterion("art_title <=", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleLike(String value) {
            addCriterion("art_title like", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleNotLike(String value) {
            addCriterion("art_title not like", value, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleIn(List<String> values) {
            addCriterion("art_title in", values, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleNotIn(List<String> values) {
            addCriterion("art_title not in", values, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleBetween(String value1, String value2) {
            addCriterion("art_title between", value1, value2, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtTitleNotBetween(String value1, String value2) {
            addCriterion("art_title not between", value1, value2, "artTitle");
            return (Criteria) this;
        }

        public Criteria andArtAbstractIsNull() {
            addCriterion("art_abstract is null");
            return (Criteria) this;
        }

        public Criteria andArtAbstractIsNotNull() {
            addCriterion("art_abstract is not null");
            return (Criteria) this;
        }

        public Criteria andArtAbstractEqualTo(String value) {
            addCriterion("art_abstract =", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractNotEqualTo(String value) {
            addCriterion("art_abstract <>", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractGreaterThan(String value) {
            addCriterion("art_abstract >", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("art_abstract >=", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractLessThan(String value) {
            addCriterion("art_abstract <", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractLessThanOrEqualTo(String value) {
            addCriterion("art_abstract <=", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractLike(String value) {
            addCriterion("art_abstract like", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractNotLike(String value) {
            addCriterion("art_abstract not like", value, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractIn(List<String> values) {
            addCriterion("art_abstract in", values, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractNotIn(List<String> values) {
            addCriterion("art_abstract not in", values, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractBetween(String value1, String value2) {
            addCriterion("art_abstract between", value1, value2, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtAbstractNotBetween(String value1, String value2) {
            addCriterion("art_abstract not between", value1, value2, "artAbstract");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdIsNull() {
            addCriterion("art_level_id is null");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdIsNotNull() {
            addCriterion("art_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdEqualTo(Long value) {
            addCriterion("art_level_id =", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdNotEqualTo(Long value) {
            addCriterion("art_level_id <>", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdGreaterThan(Long value) {
            addCriterion("art_level_id >", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("art_level_id >=", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdLessThan(Long value) {
            addCriterion("art_level_id <", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdLessThanOrEqualTo(Long value) {
            addCriterion("art_level_id <=", value, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdIn(List<Long> values) {
            addCriterion("art_level_id in", values, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdNotIn(List<Long> values) {
            addCriterion("art_level_id not in", values, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdBetween(Long value1, Long value2) {
            addCriterion("art_level_id between", value1, value2, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtLevelIdNotBetween(Long value1, Long value2) {
            addCriterion("art_level_id not between", value1, value2, "artLevelId");
            return (Criteria) this;
        }

        public Criteria andArtTagsIsNull() {
            addCriterion("art_tags is null");
            return (Criteria) this;
        }

        public Criteria andArtTagsIsNotNull() {
            addCriterion("art_tags is not null");
            return (Criteria) this;
        }

        public Criteria andArtTagsEqualTo(String value) {
            addCriterion("art_tags =", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsNotEqualTo(String value) {
            addCriterion("art_tags <>", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsGreaterThan(String value) {
            addCriterion("art_tags >", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsGreaterThanOrEqualTo(String value) {
            addCriterion("art_tags >=", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsLessThan(String value) {
            addCriterion("art_tags <", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsLessThanOrEqualTo(String value) {
            addCriterion("art_tags <=", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsLike(String value) {
            addCriterion("art_tags like", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsNotLike(String value) {
            addCriterion("art_tags not like", value, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsIn(List<String> values) {
            addCriterion("art_tags in", values, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsNotIn(List<String> values) {
            addCriterion("art_tags not in", values, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsBetween(String value1, String value2) {
            addCriterion("art_tags between", value1, value2, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtTagsNotBetween(String value1, String value2) {
            addCriterion("art_tags not between", value1, value2, "artTags");
            return (Criteria) this;
        }

        public Criteria andArtImageIsNull() {
            addCriterion("art_image is null");
            return (Criteria) this;
        }

        public Criteria andArtImageIsNotNull() {
            addCriterion("art_image is not null");
            return (Criteria) this;
        }

        public Criteria andArtImageEqualTo(String value) {
            addCriterion("art_image =", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageNotEqualTo(String value) {
            addCriterion("art_image <>", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageGreaterThan(String value) {
            addCriterion("art_image >", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageGreaterThanOrEqualTo(String value) {
            addCriterion("art_image >=", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageLessThan(String value) {
            addCriterion("art_image <", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageLessThanOrEqualTo(String value) {
            addCriterion("art_image <=", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageLike(String value) {
            addCriterion("art_image like", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageNotLike(String value) {
            addCriterion("art_image not like", value, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageIn(List<String> values) {
            addCriterion("art_image in", values, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageNotIn(List<String> values) {
            addCriterion("art_image not in", values, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageBetween(String value1, String value2) {
            addCriterion("art_image between", value1, value2, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtImageNotBetween(String value1, String value2) {
            addCriterion("art_image not between", value1, value2, "artImage");
            return (Criteria) this;
        }

        public Criteria andArtFromIsNull() {
            addCriterion("art_from is null");
            return (Criteria) this;
        }

        public Criteria andArtFromIsNotNull() {
            addCriterion("art_from is not null");
            return (Criteria) this;
        }

        public Criteria andArtFromEqualTo(String value) {
            addCriterion("art_from =", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromNotEqualTo(String value) {
            addCriterion("art_from <>", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromGreaterThan(String value) {
            addCriterion("art_from >", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromGreaterThanOrEqualTo(String value) {
            addCriterion("art_from >=", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromLessThan(String value) {
            addCriterion("art_from <", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromLessThanOrEqualTo(String value) {
            addCriterion("art_from <=", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromLike(String value) {
            addCriterion("art_from like", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromNotLike(String value) {
            addCriterion("art_from not like", value, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromIn(List<String> values) {
            addCriterion("art_from in", values, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromNotIn(List<String> values) {
            addCriterion("art_from not in", values, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromBetween(String value1, String value2) {
            addCriterion("art_from between", value1, value2, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtFromNotBetween(String value1, String value2) {
            addCriterion("art_from not between", value1, value2, "artFrom");
            return (Criteria) this;
        }

        public Criteria andArtAuthorIsNull() {
            addCriterion("art_author is null");
            return (Criteria) this;
        }

        public Criteria andArtAuthorIsNotNull() {
            addCriterion("art_author is not null");
            return (Criteria) this;
        }

        public Criteria andArtAuthorEqualTo(String value) {
            addCriterion("art_author =", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorNotEqualTo(String value) {
            addCriterion("art_author <>", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorGreaterThan(String value) {
            addCriterion("art_author >", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("art_author >=", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorLessThan(String value) {
            addCriterion("art_author <", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorLessThanOrEqualTo(String value) {
            addCriterion("art_author <=", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorLike(String value) {
            addCriterion("art_author like", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorNotLike(String value) {
            addCriterion("art_author not like", value, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorIn(List<String> values) {
            addCriterion("art_author in", values, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorNotIn(List<String> values) {
            addCriterion("art_author not in", values, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorBetween(String value1, String value2) {
            addCriterion("art_author between", value1, value2, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtAuthorNotBetween(String value1, String value2) {
            addCriterion("art_author not between", value1, value2, "artAuthor");
            return (Criteria) this;
        }

        public Criteria andArtStatusIsNull() {
            addCriterion("art_status is null");
            return (Criteria) this;
        }

        public Criteria andArtStatusIsNotNull() {
            addCriterion("art_status is not null");
            return (Criteria) this;
        }

        public Criteria andArtStatusEqualTo(Integer value) {
            addCriterion("art_status =", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusNotEqualTo(Integer value) {
            addCriterion("art_status <>", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusGreaterThan(Integer value) {
            addCriterion("art_status >", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("art_status >=", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusLessThan(Integer value) {
            addCriterion("art_status <", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusLessThanOrEqualTo(Integer value) {
            addCriterion("art_status <=", value, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusIn(List<Integer> values) {
            addCriterion("art_status in", values, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusNotIn(List<Integer> values) {
            addCriterion("art_status not in", values, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusBetween(Integer value1, Integer value2) {
            addCriterion("art_status between", value1, value2, "artStatus");
            return (Criteria) this;
        }

        public Criteria andArtStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("art_status not between", value1, value2, "artStatus");
            return (Criteria) this;
        }

        public Criteria andLikesIsNull() {
            addCriterion("likes is null");
            return (Criteria) this;
        }

        public Criteria andLikesIsNotNull() {
            addCriterion("likes is not null");
            return (Criteria) this;
        }

        public Criteria andLikesEqualTo(Integer value) {
            addCriterion("likes =", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesNotEqualTo(Integer value) {
            addCriterion("likes <>", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesGreaterThan(Integer value) {
            addCriterion("likes >", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesGreaterThanOrEqualTo(Integer value) {
            addCriterion("likes >=", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesLessThan(Integer value) {
            addCriterion("likes <", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesLessThanOrEqualTo(Integer value) {
            addCriterion("likes <=", value, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesIn(List<Integer> values) {
            addCriterion("likes in", values, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesNotIn(List<Integer> values) {
            addCriterion("likes not in", values, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesBetween(Integer value1, Integer value2) {
            addCriterion("likes between", value1, value2, "likes");
            return (Criteria) this;
        }

        public Criteria andLikesNotBetween(Integer value1, Integer value2) {
            addCriterion("likes not between", value1, value2, "likes");
            return (Criteria) this;
        }

        public Criteria andVisitCntIsNull() {
            addCriterion("visit_cnt is null");
            return (Criteria) this;
        }

        public Criteria andVisitCntIsNotNull() {
            addCriterion("visit_cnt is not null");
            return (Criteria) this;
        }

        public Criteria andVisitCntEqualTo(Integer value) {
            addCriterion("visit_cnt =", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntNotEqualTo(Integer value) {
            addCriterion("visit_cnt <>", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntGreaterThan(Integer value) {
            addCriterion("visit_cnt >", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("visit_cnt >=", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntLessThan(Integer value) {
            addCriterion("visit_cnt <", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntLessThanOrEqualTo(Integer value) {
            addCriterion("visit_cnt <=", value, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntIn(List<Integer> values) {
            addCriterion("visit_cnt in", values, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntNotIn(List<Integer> values) {
            addCriterion("visit_cnt not in", values, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntBetween(Integer value1, Integer value2) {
            addCriterion("visit_cnt between", value1, value2, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andVisitCntNotBetween(Integer value1, Integer value2) {
            addCriterion("visit_cnt not between", value1, value2, "visitCnt");
            return (Criteria) this;
        }

        public Criteria andArtSortIsNull() {
            addCriterion("art_sort is null");
            return (Criteria) this;
        }

        public Criteria andArtSortIsNotNull() {
            addCriterion("art_sort is not null");
            return (Criteria) this;
        }

        public Criteria andArtSortEqualTo(Integer value) {
            addCriterion("art_sort =", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortNotEqualTo(Integer value) {
            addCriterion("art_sort <>", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortGreaterThan(Integer value) {
            addCriterion("art_sort >", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("art_sort >=", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortLessThan(Integer value) {
            addCriterion("art_sort <", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortLessThanOrEqualTo(Integer value) {
            addCriterion("art_sort <=", value, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortIn(List<Integer> values) {
            addCriterion("art_sort in", values, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortNotIn(List<Integer> values) {
            addCriterion("art_sort not in", values, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortBetween(Integer value1, Integer value2) {
            addCriterion("art_sort between", value1, value2, "artSort");
            return (Criteria) this;
        }

        public Criteria andArtSortNotBetween(Integer value1, Integer value2) {
            addCriterion("art_sort not between", value1, value2, "artSort");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNull() {
            addCriterion("is_top is null");
            return (Criteria) this;
        }

        public Criteria andIsTopIsNotNull() {
            addCriterion("is_top is not null");
            return (Criteria) this;
        }

        public Criteria andIsTopEqualTo(Byte value) {
            addCriterion("is_top =", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotEqualTo(Byte value) {
            addCriterion("is_top <>", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThan(Byte value) {
            addCriterion("is_top >", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_top >=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThan(Byte value) {
            addCriterion("is_top <", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopLessThanOrEqualTo(Byte value) {
            addCriterion("is_top <=", value, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopIn(List<Byte> values) {
            addCriterion("is_top in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotIn(List<Byte> values) {
            addCriterion("is_top not in", values, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopBetween(Byte value1, Byte value2) {
            addCriterion("is_top between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andIsTopNotBetween(Byte value1, Byte value2) {
            addCriterion("is_top not between", value1, value2, "isTop");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Long value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Long value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Long value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Long value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Long value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Long> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Long> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Long value1, Long value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Long value1, Long value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Long value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Long value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Long value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Long value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Long value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Long> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Long> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Long value1, Long value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Long value1, Long value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeIsNull() {
            addCriterion("pub_time is null");
            return (Criteria) this;
        }

        public Criteria andPubTimeIsNotNull() {
            addCriterion("pub_time is not null");
            return (Criteria) this;
        }

        public Criteria andPubTimeEqualTo(Long value) {
            addCriterion("pub_time =", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotEqualTo(Long value) {
            addCriterion("pub_time <>", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeGreaterThan(Long value) {
            addCriterion("pub_time >", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("pub_time >=", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeLessThan(Long value) {
            addCriterion("pub_time <", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeLessThanOrEqualTo(Long value) {
            addCriterion("pub_time <=", value, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeIn(List<Long> values) {
            addCriterion("pub_time in", values, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotIn(List<Long> values) {
            addCriterion("pub_time not in", values, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeBetween(Long value1, Long value2) {
            addCriterion("pub_time between", value1, value2, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPubTimeNotBetween(Long value1, Long value2) {
            addCriterion("pub_time not between", value1, value2, "pubTime");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNull() {
            addCriterion("platform_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNotNull() {
            addCriterion("platform_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdEqualTo(Long value) {
            addCriterion("platform_id =", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotEqualTo(Long value) {
            addCriterion("platform_id <>", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThan(Long value) {
            addCriterion("platform_id >", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThanOrEqualTo(Long value) {
            addCriterion("platform_id >=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThan(Long value) {
            addCriterion("platform_id <", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThanOrEqualTo(Long value) {
            addCriterion("platform_id <=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIn(List<Long> values) {
            addCriterion("platform_id in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotIn(List<Long> values) {
            addCriterion("platform_id not in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdBetween(Long value1, Long value2) {
            addCriterion("platform_id between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotBetween(Long value1, Long value2) {
            addCriterion("platform_id not between", value1, value2, "platformId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_article
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_article
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}