package com.hqjcloud.article.beans;

public class ArticleLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.level_parentId
     *
     * @mbg.generated
     */
    private Long levelParentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.level_status
     *
     * @mbg.generated
     */
    private Byte levelStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article_level.modifytime
     *
     * @mbg.generated
     */
    private Long modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.longid
     *
     * @return the value of hqj_article_level.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.longid
     *
     * @param longid the value for hqj_article_level.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.level_name
     *
     * @return the value of hqj_article_level.level_name
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.level_name
     *
     * @param levelName the value for hqj_article_level.level_name
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.level_parentId
     *
     * @return the value of hqj_article_level.level_parentId
     *
     * @mbg.generated
     */
    public Long getLevelParentid() {
        return levelParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.level_parentId
     *
     * @param levelParentid the value for hqj_article_level.level_parentId
     *
     * @mbg.generated
     */
    public void setLevelParentid(Long levelParentid) {
        this.levelParentid = levelParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.level_status
     *
     * @return the value of hqj_article_level.level_status
     *
     * @mbg.generated
     */
    public Byte getLevelStatus() {
        return levelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.level_status
     *
     * @param levelStatus the value for hqj_article_level.level_status
     *
     * @mbg.generated
     */
    public void setLevelStatus(Byte levelStatus) {
        this.levelStatus = levelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.addtime
     *
     * @return the value of hqj_article_level.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.addtime
     *
     * @param addtime the value for hqj_article_level.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article_level.modifytime
     *
     * @return the value of hqj_article_level.modifytime
     *
     * @mbg.generated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article_level.modifytime
     *
     * @param modifytime the value for hqj_article_level.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }
}