package com.hqjcloud.article.beans;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_title
     *
     * @mbg.generated
     */
    private String artTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_abstract
     *
     * @mbg.generated
     */
    private String artAbstract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_level_id
     *
     * @mbg.generated
     */
    private Long artLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_tags
     *
     * @mbg.generated
     */
    private String artTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_image
     *
     * @mbg.generated
     */
    private String artImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_from
     *
     * @mbg.generated
     */
    private String artFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_author
     *
     * @mbg.generated
     */
    private String artAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_status
     *
     * @mbg.generated
     */
    private Integer artStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.likes
     *
     * @mbg.generated
     */
    private Integer likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.visit_cnt
     *
     * @mbg.generated
     */
    private Integer visitCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_sort
     *
     * @mbg.generated
     */
    private Integer artSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.is_top
     *
     * @mbg.generated
     */
    private Byte isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.add_time
     *
     * @mbg.generated
     */
    private Long addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.pub_time
     *
     * @mbg.generated
     */
    private Long pubTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.platform_id
     *
     * @mbg.generated
     */
    private Long platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_article.art_content
     *
     * @mbg.generated
     */
    private String artContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.longid
     *
     * @return the value of hqj_article.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.longid
     *
     * @param longid the value for hqj_article.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_title
     *
     * @return the value of hqj_article.art_title
     *
     * @mbg.generated
     */
    public String getArtTitle() {
        return artTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_title
     *
     * @param artTitle the value for hqj_article.art_title
     *
     * @mbg.generated
     */
    public void setArtTitle(String artTitle) {
        this.artTitle = artTitle == null ? null : artTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_abstract
     *
     * @return the value of hqj_article.art_abstract
     *
     * @mbg.generated
     */
    public String getArtAbstract() {
        return artAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_abstract
     *
     * @param artAbstract the value for hqj_article.art_abstract
     *
     * @mbg.generated
     */
    public void setArtAbstract(String artAbstract) {
        this.artAbstract = artAbstract == null ? null : artAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_level_id
     *
     * @return the value of hqj_article.art_level_id
     *
     * @mbg.generated
     */
    public Long getArtLevelId() {
        return artLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_level_id
     *
     * @param artLevelId the value for hqj_article.art_level_id
     *
     * @mbg.generated
     */
    public void setArtLevelId(Long artLevelId) {
        this.artLevelId = artLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_tags
     *
     * @return the value of hqj_article.art_tags
     *
     * @mbg.generated
     */
    public String getArtTags() {
        return artTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_tags
     *
     * @param artTags the value for hqj_article.art_tags
     *
     * @mbg.generated
     */
    public void setArtTags(String artTags) {
        this.artTags = artTags == null ? null : artTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_image
     *
     * @return the value of hqj_article.art_image
     *
     * @mbg.generated
     */
    public String getArtImage() {
        return artImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_image
     *
     * @param artImage the value for hqj_article.art_image
     *
     * @mbg.generated
     */
    public void setArtImage(String artImage) {
        this.artImage = artImage == null ? null : artImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_from
     *
     * @return the value of hqj_article.art_from
     *
     * @mbg.generated
     */
    public String getArtFrom() {
        return artFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_from
     *
     * @param artFrom the value for hqj_article.art_from
     *
     * @mbg.generated
     */
    public void setArtFrom(String artFrom) {
        this.artFrom = artFrom == null ? null : artFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_author
     *
     * @return the value of hqj_article.art_author
     *
     * @mbg.generated
     */
    public String getArtAuthor() {
        return artAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_author
     *
     * @param artAuthor the value for hqj_article.art_author
     *
     * @mbg.generated
     */
    public void setArtAuthor(String artAuthor) {
        this.artAuthor = artAuthor == null ? null : artAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_status
     *
     * @return the value of hqj_article.art_status
     *
     * @mbg.generated
     */
    public Integer getArtStatus() {
        return artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_status
     *
     * @param artStatus the value for hqj_article.art_status
     *
     * @mbg.generated
     */
    public void setArtStatus(Integer artStatus) {
        this.artStatus = artStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.likes
     *
     * @return the value of hqj_article.likes
     *
     * @mbg.generated
     */
    public Integer getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.likes
     *
     * @param likes the value for hqj_article.likes
     *
     * @mbg.generated
     */
    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.visit_cnt
     *
     * @return the value of hqj_article.visit_cnt
     *
     * @mbg.generated
     */
    public Integer getVisitCnt() {
        return visitCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.visit_cnt
     *
     * @param visitCnt the value for hqj_article.visit_cnt
     *
     * @mbg.generated
     */
    public void setVisitCnt(Integer visitCnt) {
        this.visitCnt = visitCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_sort
     *
     * @return the value of hqj_article.art_sort
     *
     * @mbg.generated
     */
    public Integer getArtSort() {
        return artSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_sort
     *
     * @param artSort the value for hqj_article.art_sort
     *
     * @mbg.generated
     */
    public void setArtSort(Integer artSort) {
        this.artSort = artSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.is_top
     *
     * @return the value of hqj_article.is_top
     *
     * @mbg.generated
     */
    public Byte getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.is_top
     *
     * @param isTop the value for hqj_article.is_top
     *
     * @mbg.generated
     */
    public void setIsTop(Byte isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.add_time
     *
     * @return the value of hqj_article.add_time
     *
     * @mbg.generated
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.add_time
     *
     * @param addTime the value for hqj_article.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.modify_time
     *
     * @return the value of hqj_article.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.modify_time
     *
     * @param modifyTime the value for hqj_article.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.pub_time
     *
     * @return the value of hqj_article.pub_time
     *
     * @mbg.generated
     */
    public Long getPubTime() {
        return pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.pub_time
     *
     * @param pubTime the value for hqj_article.pub_time
     *
     * @mbg.generated
     */
    public void setPubTime(Long pubTime) {
        this.pubTime = pubTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.platform_id
     *
     * @return the value of hqj_article.platform_id
     *
     * @mbg.generated
     */
    public Long getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.platform_id
     *
     * @param platformId the value for hqj_article.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Long platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_article.art_content
     *
     * @return the value of hqj_article.art_content
     *
     * @mbg.generated
     */
    public String getArtContent() {
        return artContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_article.art_content
     *
     * @param artContent the value for hqj_article.art_content
     *
     * @mbg.generated
     */
    public void setArtContent(String artContent) {
        this.artContent = artContent == null ? null : artContent.trim();
    }
}