package com.hqjcloud.article.beans;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_tag.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_tag.tag_name
     *
     * @mbg.generated
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_tag.add_time
     *
     * @mbg.generated
     */
    private Long addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_tag.tag_status
     *
     * @mbg.generated
     */
    private Byte tagStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_tag.longid
     *
     * @return the value of hqj_tag.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_tag.longid
     *
     * @param longid the value for hqj_tag.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_tag.tag_name
     *
     * @return the value of hqj_tag.tag_name
     *
     * @mbg.generated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_tag.tag_name
     *
     * @param tagName the value for hqj_tag.tag_name
     *
     * @mbg.generated
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_tag.add_time
     *
     * @return the value of hqj_tag.add_time
     *
     * @mbg.generated
     */
    public Long getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_tag.add_time
     *
     * @param addTime the value for hqj_tag.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_tag.tag_status
     *
     * @return the value of hqj_tag.tag_status
     *
     * @mbg.generated
     */
    public Byte getTagStatus() {
        return tagStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_tag.tag_status
     *
     * @param tagStatus the value for hqj_tag.tag_status
     *
     * @mbg.generated
     */
    public void setTagStatus(Byte tagStatus) {
        this.tagStatus = tagStatus;
    }
}