server:
  port: 8881
  servlet:
    context-path: /
#忽略权限拦截
management:
  security:
    enabled: false

spring:
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.175:3306/ArticleSystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wuqian
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml,mapper/**/*.xml
  type-aliases-package: com.oauth.server.beans
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql