package com.hqjcloud.article.mapper.base;

import com.hqjcloud.article.beans.ArticleClassRelation;
import com.hqjcloud.article.beans.ArticleClassRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleClassRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    long countByExample(ArticleClassRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleClassRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int insert(ArticleClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int insertSelective(ArticleClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    List<ArticleClassRelation> selectByExample(ArticleClassRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    ArticleClassRelation selectByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleClassRelation record, @Param("example") ArticleClassRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleClassRelation record, @Param("example") ArticleClassRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleClassRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclassrelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleClassRelation record);
}