package com.hqjcloud.article.mapper.base;

import com.hqjcloud.article.beans.ArticleTagRelation;
import com.hqjcloud.article.beans.ArticleTagRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    long countByExample(ArticleTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int insert(ArticleTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int insertSelective(ArticleTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    List<ArticleTagRelation> selectByExample(ArticleTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    ArticleTagRelation selectByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleTagRelation record, @Param("example") ArticleTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleTagRelation record, @Param("example") ArticleTagRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articletag_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleTagRelation record);
}