package com.hqjcloud.article.mapper.base;

import com.hqjcloud.article.beans.ArticleClass;
import com.hqjcloud.article.beans.ArticleClassExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ArticleClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    long countByExample(ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int insert(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int insertSelective(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    List<ArticleClass> selectByExample(ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    ArticleClass selectByPrimaryKey(Long longid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleClass record, @Param("example") ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleClass record, @Param("example") ArticleClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_articleclass
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleClass record);
}