server:
  port: 8010
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /static/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  application:
    name: hqjcloud-articlesystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.175:3306/articleSystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wuqian
