server:
  port: 8011
  servlet:
    context-path: /
security:
  basic:
    enabled: false

spring:
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
  application:
    name: @pom.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.175:3306/ArticleSystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wuqian
mybatis:
  config-location: classpath:mybatis-com.oauth.server.config.xml
  mapper-locations: classpath:mapper/*.xml,mapper/**/*.xml
  type-aliases-package: com.hqjcloud.upms.beans
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jwt:
  secret: secret
  expiration: 7200000
  token: Authorization