package com.hqjcloud.upms.beans;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_user_role.longid
     *
     * @mbg.generated
     */
    private Long longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_user_role.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_user_role.roleid
     *
     * @mbg.generated
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_user_role.addtime
     *
     * @mbg.generated
     */
    private Long addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_user_role.modifytime
     *
     * @mbg.generated
     */
    private Long modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_user_role.longid
     *
     * @return the value of hqj_user_role.longid
     *
     * @mbg.generated
     */
    public Long getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_user_role.longid
     *
     * @param longid the value for hqj_user_role.longid
     *
     * @mbg.generated
     */
    public void setLongid(Long longid) {
        this.longid = longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_user_role.userid
     *
     * @return the value of hqj_user_role.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_user_role.userid
     *
     * @param userid the value for hqj_user_role.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_user_role.roleid
     *
     * @return the value of hqj_user_role.roleid
     *
     * @mbg.generated
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_user_role.roleid
     *
     * @param roleid the value for hqj_user_role.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_user_role.addtime
     *
     * @return the value of hqj_user_role.addtime
     *
     * @mbg.generated
     */
    public Long getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_user_role.addtime
     *
     * @param addtime the value for hqj_user_role.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Long addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_user_role.modifytime
     *
     * @return the value of hqj_user_role.modifytime
     *
     * @mbg.generated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_user_role.modifytime
     *
     * @param modifytime the value for hqj_user_role.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }
}