server:
  port: 8010
  servlet:
    context-path: /

spring:
  http:
    encoding:
      force-response: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      additional-paths: src/main/java,src/main/resources
  thymeleaf:
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.175:3306/ArticleSystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wuqian
  servlet:
    multipart:
      max-file-size: 50Mb #单个文件大小
      max-request-size: 100Mb #即总上传的数据大小
mybatis:
  config-location: classpath:mybatis-com.oauth.server.config.xml
  mapper-locations: classpath:mapper/*.xml,mapper/**/*.xml
  type-aliases-package: com.hqjcloud.article.beans
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql