server:
  port: 8010
  servlet:
    context-path: /

spring:
  application:
    name: @pom.artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.175:3306/tradesystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wuqian
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true