package com.oauth.server.beans;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.longid
     *
     * @mbg.generated
     */
    private String longid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.clientId
     *
     * @mbg.generated
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.resourceIds
     *
     * @mbg.generated
     */
    private String resourceids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.isSecretRequired
     *
     * @mbg.generated
     */
    private Boolean issecretrequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.clientSecret
     *
     * @mbg.generated
     */
    private String clientsecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.isScoped
     *
     * @mbg.generated
     */
    private Boolean isscoped;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.authorizedGrantTypes
     *
     * @mbg.generated
     */
    private String authorizedgranttypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.registeredRedirectUri
     *
     * @mbg.generated
     */
    private String registeredredirecturi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.authorities
     *
     * @mbg.generated
     */
    private String authorities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.isAutoApprove
     *
     * @mbg.generated
     */
    private Boolean isautoapprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.accessTokenValiditySeconds
     *
     * @mbg.generated
     */
    private Integer accesstokenvalidityseconds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hqj_client.refreshTokenValiditySeconds
     *
     * @mbg.generated
     */
    private Integer refreshtokenvalidityseconds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.longid
     *
     * @return the value of hqj_client.longid
     *
     * @mbg.generated
     */
    public String getLongid() {
        return longid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.longid
     *
     * @param longid the value for hqj_client.longid
     *
     * @mbg.generated
     */
    public void setLongid(String longid) {
        this.longid = longid == null ? null : longid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.clientId
     *
     * @return the value of hqj_client.clientId
     *
     * @mbg.generated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.clientId
     *
     * @param clientid the value for hqj_client.clientId
     *
     * @mbg.generated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.resourceIds
     *
     * @return the value of hqj_client.resourceIds
     *
     * @mbg.generated
     */
    public String getResourceids() {
        return resourceids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.resourceIds
     *
     * @param resourceids the value for hqj_client.resourceIds
     *
     * @mbg.generated
     */
    public void setResourceids(String resourceids) {
        this.resourceids = resourceids == null ? null : resourceids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.isSecretRequired
     *
     * @return the value of hqj_client.isSecretRequired
     *
     * @mbg.generated
     */
    public Boolean getIssecretrequired() {
        return issecretrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.isSecretRequired
     *
     * @param issecretrequired the value for hqj_client.isSecretRequired
     *
     * @mbg.generated
     */
    public void setIssecretrequired(Boolean issecretrequired) {
        this.issecretrequired = issecretrequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.clientSecret
     *
     * @return the value of hqj_client.clientSecret
     *
     * @mbg.generated
     */
    public String getClientsecret() {
        return clientsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.clientSecret
     *
     * @param clientsecret the value for hqj_client.clientSecret
     *
     * @mbg.generated
     */
    public void setClientsecret(String clientsecret) {
        this.clientsecret = clientsecret == null ? null : clientsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.isScoped
     *
     * @return the value of hqj_client.isScoped
     *
     * @mbg.generated
     */
    public Boolean getIsscoped() {
        return isscoped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.isScoped
     *
     * @param isscoped the value for hqj_client.isScoped
     *
     * @mbg.generated
     */
    public void setIsscoped(Boolean isscoped) {
        this.isscoped = isscoped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.scope
     *
     * @return the value of hqj_client.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.scope
     *
     * @param scope the value for hqj_client.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.authorizedGrantTypes
     *
     * @return the value of hqj_client.authorizedGrantTypes
     *
     * @mbg.generated
     */
    public String getAuthorizedgranttypes() {
        return authorizedgranttypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.authorizedGrantTypes
     *
     * @param authorizedgranttypes the value for hqj_client.authorizedGrantTypes
     *
     * @mbg.generated
     */
    public void setAuthorizedgranttypes(String authorizedgranttypes) {
        this.authorizedgranttypes = authorizedgranttypes == null ? null : authorizedgranttypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.registeredRedirectUri
     *
     * @return the value of hqj_client.registeredRedirectUri
     *
     * @mbg.generated
     */
    public String getRegisteredredirecturi() {
        return registeredredirecturi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.registeredRedirectUri
     *
     * @param registeredredirecturi the value for hqj_client.registeredRedirectUri
     *
     * @mbg.generated
     */
    public void setRegisteredredirecturi(String registeredredirecturi) {
        this.registeredredirecturi = registeredredirecturi == null ? null : registeredredirecturi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.authorities
     *
     * @return the value of hqj_client.authorities
     *
     * @mbg.generated
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.authorities
     *
     * @param authorities the value for hqj_client.authorities
     *
     * @mbg.generated
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities == null ? null : authorities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.isAutoApprove
     *
     * @return the value of hqj_client.isAutoApprove
     *
     * @mbg.generated
     */
    public Boolean getIsautoapprove() {
        return isautoapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.isAutoApprove
     *
     * @param isautoapprove the value for hqj_client.isAutoApprove
     *
     * @mbg.generated
     */
    public void setIsautoapprove(Boolean isautoapprove) {
        this.isautoapprove = isautoapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.accessTokenValiditySeconds
     *
     * @return the value of hqj_client.accessTokenValiditySeconds
     *
     * @mbg.generated
     */
    public Integer getAccesstokenvalidityseconds() {
        return accesstokenvalidityseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.accessTokenValiditySeconds
     *
     * @param accesstokenvalidityseconds the value for hqj_client.accessTokenValiditySeconds
     *
     * @mbg.generated
     */
    public void setAccesstokenvalidityseconds(Integer accesstokenvalidityseconds) {
        this.accesstokenvalidityseconds = accesstokenvalidityseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hqj_client.refreshTokenValiditySeconds
     *
     * @return the value of hqj_client.refreshTokenValiditySeconds
     *
     * @mbg.generated
     */
    public Integer getRefreshtokenvalidityseconds() {
        return refreshtokenvalidityseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hqj_client.refreshTokenValiditySeconds
     *
     * @param refreshtokenvalidityseconds the value for hqj_client.refreshTokenValiditySeconds
     *
     * @mbg.generated
     */
    public void setRefreshtokenvalidityseconds(Integer refreshtokenvalidityseconds) {
        this.refreshtokenvalidityseconds = refreshtokenvalidityseconds;
    }
}