package com.oauth.server.beans;

import java.util.ArrayList;
import java.util.List;

public class ClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public ClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLongidIsNull() {
            addCriterion("longid is null");
            return (Criteria) this;
        }

        public Criteria andLongidIsNotNull() {
            addCriterion("longid is not null");
            return (Criteria) this;
        }

        public Criteria andLongidEqualTo(String value) {
            addCriterion("longid =", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotEqualTo(String value) {
            addCriterion("longid <>", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidGreaterThan(String value) {
            addCriterion("longid >", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidGreaterThanOrEqualTo(String value) {
            addCriterion("longid >=", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidLessThan(String value) {
            addCriterion("longid <", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidLessThanOrEqualTo(String value) {
            addCriterion("longid <=", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidLike(String value) {
            addCriterion("longid like", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotLike(String value) {
            addCriterion("longid not like", value, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidIn(List<String> values) {
            addCriterion("longid in", values, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotIn(List<String> values) {
            addCriterion("longid not in", values, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidBetween(String value1, String value2) {
            addCriterion("longid between", value1, value2, "longid");
            return (Criteria) this;
        }

        public Criteria andLongidNotBetween(String value1, String value2) {
            addCriterion("longid not between", value1, value2, "longid");
            return (Criteria) this;
        }

        public Criteria andClientidIsNull() {
            addCriterion("clientId is null");
            return (Criteria) this;
        }

        public Criteria andClientidIsNotNull() {
            addCriterion("clientId is not null");
            return (Criteria) this;
        }

        public Criteria andClientidEqualTo(String value) {
            addCriterion("clientId =", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotEqualTo(String value) {
            addCriterion("clientId <>", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThan(String value) {
            addCriterion("clientId >", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThanOrEqualTo(String value) {
            addCriterion("clientId >=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThan(String value) {
            addCriterion("clientId <", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThanOrEqualTo(String value) {
            addCriterion("clientId <=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLike(String value) {
            addCriterion("clientId like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotLike(String value) {
            addCriterion("clientId not like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidIn(List<String> values) {
            addCriterion("clientId in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotIn(List<String> values) {
            addCriterion("clientId not in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidBetween(String value1, String value2) {
            addCriterion("clientId between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotBetween(String value1, String value2) {
            addCriterion("clientId not between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andResourceidsIsNull() {
            addCriterion("resourceIds is null");
            return (Criteria) this;
        }

        public Criteria andResourceidsIsNotNull() {
            addCriterion("resourceIds is not null");
            return (Criteria) this;
        }

        public Criteria andResourceidsEqualTo(String value) {
            addCriterion("resourceIds =", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsNotEqualTo(String value) {
            addCriterion("resourceIds <>", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsGreaterThan(String value) {
            addCriterion("resourceIds >", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsGreaterThanOrEqualTo(String value) {
            addCriterion("resourceIds >=", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsLessThan(String value) {
            addCriterion("resourceIds <", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsLessThanOrEqualTo(String value) {
            addCriterion("resourceIds <=", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsLike(String value) {
            addCriterion("resourceIds like", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsNotLike(String value) {
            addCriterion("resourceIds not like", value, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsIn(List<String> values) {
            addCriterion("resourceIds in", values, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsNotIn(List<String> values) {
            addCriterion("resourceIds not in", values, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsBetween(String value1, String value2) {
            addCriterion("resourceIds between", value1, value2, "resourceids");
            return (Criteria) this;
        }

        public Criteria andResourceidsNotBetween(String value1, String value2) {
            addCriterion("resourceIds not between", value1, value2, "resourceids");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredIsNull() {
            addCriterion("isSecretRequired is null");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredIsNotNull() {
            addCriterion("isSecretRequired is not null");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredEqualTo(Boolean value) {
            addCriterion("isSecretRequired =", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredNotEqualTo(Boolean value) {
            addCriterion("isSecretRequired <>", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredGreaterThan(Boolean value) {
            addCriterion("isSecretRequired >", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isSecretRequired >=", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredLessThan(Boolean value) {
            addCriterion("isSecretRequired <", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredLessThanOrEqualTo(Boolean value) {
            addCriterion("isSecretRequired <=", value, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredIn(List<Boolean> values) {
            addCriterion("isSecretRequired in", values, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredNotIn(List<Boolean> values) {
            addCriterion("isSecretRequired not in", values, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredBetween(Boolean value1, Boolean value2) {
            addCriterion("isSecretRequired between", value1, value2, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andIssecretrequiredNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isSecretRequired not between", value1, value2, "issecretrequired");
            return (Criteria) this;
        }

        public Criteria andClientsecretIsNull() {
            addCriterion("clientSecret is null");
            return (Criteria) this;
        }

        public Criteria andClientsecretIsNotNull() {
            addCriterion("clientSecret is not null");
            return (Criteria) this;
        }

        public Criteria andClientsecretEqualTo(String value) {
            addCriterion("clientSecret =", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretNotEqualTo(String value) {
            addCriterion("clientSecret <>", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretGreaterThan(String value) {
            addCriterion("clientSecret >", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretGreaterThanOrEqualTo(String value) {
            addCriterion("clientSecret >=", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretLessThan(String value) {
            addCriterion("clientSecret <", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretLessThanOrEqualTo(String value) {
            addCriterion("clientSecret <=", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretLike(String value) {
            addCriterion("clientSecret like", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretNotLike(String value) {
            addCriterion("clientSecret not like", value, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretIn(List<String> values) {
            addCriterion("clientSecret in", values, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretNotIn(List<String> values) {
            addCriterion("clientSecret not in", values, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretBetween(String value1, String value2) {
            addCriterion("clientSecret between", value1, value2, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andClientsecretNotBetween(String value1, String value2) {
            addCriterion("clientSecret not between", value1, value2, "clientsecret");
            return (Criteria) this;
        }

        public Criteria andIsscopedIsNull() {
            addCriterion("isScoped is null");
            return (Criteria) this;
        }

        public Criteria andIsscopedIsNotNull() {
            addCriterion("isScoped is not null");
            return (Criteria) this;
        }

        public Criteria andIsscopedEqualTo(Boolean value) {
            addCriterion("isScoped =", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedNotEqualTo(Boolean value) {
            addCriterion("isScoped <>", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedGreaterThan(Boolean value) {
            addCriterion("isScoped >", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isScoped >=", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedLessThan(Boolean value) {
            addCriterion("isScoped <", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedLessThanOrEqualTo(Boolean value) {
            addCriterion("isScoped <=", value, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedIn(List<Boolean> values) {
            addCriterion("isScoped in", values, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedNotIn(List<Boolean> values) {
            addCriterion("isScoped not in", values, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedBetween(Boolean value1, Boolean value2) {
            addCriterion("isScoped between", value1, value2, "isscoped");
            return (Criteria) this;
        }

        public Criteria andIsscopedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isScoped not between", value1, value2, "isscoped");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesIsNull() {
            addCriterion("authorizedGrantTypes is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesIsNotNull() {
            addCriterion("authorizedGrantTypes is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesEqualTo(String value) {
            addCriterion("authorizedGrantTypes =", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesNotEqualTo(String value) {
            addCriterion("authorizedGrantTypes <>", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesGreaterThan(String value) {
            addCriterion("authorizedGrantTypes >", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesGreaterThanOrEqualTo(String value) {
            addCriterion("authorizedGrantTypes >=", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesLessThan(String value) {
            addCriterion("authorizedGrantTypes <", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesLessThanOrEqualTo(String value) {
            addCriterion("authorizedGrantTypes <=", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesLike(String value) {
            addCriterion("authorizedGrantTypes like", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesNotLike(String value) {
            addCriterion("authorizedGrantTypes not like", value, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesIn(List<String> values) {
            addCriterion("authorizedGrantTypes in", values, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesNotIn(List<String> values) {
            addCriterion("authorizedGrantTypes not in", values, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesBetween(String value1, String value2) {
            addCriterion("authorizedGrantTypes between", value1, value2, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedgranttypesNotBetween(String value1, String value2) {
            addCriterion("authorizedGrantTypes not between", value1, value2, "authorizedgranttypes");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiIsNull() {
            addCriterion("registeredRedirectUri is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiIsNotNull() {
            addCriterion("registeredRedirectUri is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiEqualTo(String value) {
            addCriterion("registeredRedirectUri =", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiNotEqualTo(String value) {
            addCriterion("registeredRedirectUri <>", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiGreaterThan(String value) {
            addCriterion("registeredRedirectUri >", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiGreaterThanOrEqualTo(String value) {
            addCriterion("registeredRedirectUri >=", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiLessThan(String value) {
            addCriterion("registeredRedirectUri <", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiLessThanOrEqualTo(String value) {
            addCriterion("registeredRedirectUri <=", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiLike(String value) {
            addCriterion("registeredRedirectUri like", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiNotLike(String value) {
            addCriterion("registeredRedirectUri not like", value, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiIn(List<String> values) {
            addCriterion("registeredRedirectUri in", values, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiNotIn(List<String> values) {
            addCriterion("registeredRedirectUri not in", values, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiBetween(String value1, String value2) {
            addCriterion("registeredRedirectUri between", value1, value2, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andRegisteredredirecturiNotBetween(String value1, String value2) {
            addCriterion("registeredRedirectUri not between", value1, value2, "registeredredirecturi");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNull() {
            addCriterion("authorities is null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNotNull() {
            addCriterion("authorities is not null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesEqualTo(String value) {
            addCriterion("authorities =", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotEqualTo(String value) {
            addCriterion("authorities <>", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThan(String value) {
            addCriterion("authorities >", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThanOrEqualTo(String value) {
            addCriterion("authorities >=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThan(String value) {
            addCriterion("authorities <", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThanOrEqualTo(String value) {
            addCriterion("authorities <=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLike(String value) {
            addCriterion("authorities like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotLike(String value) {
            addCriterion("authorities not like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIn(List<String> values) {
            addCriterion("authorities in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotIn(List<String> values) {
            addCriterion("authorities not in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesBetween(String value1, String value2) {
            addCriterion("authorities between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotBetween(String value1, String value2) {
            addCriterion("authorities not between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveIsNull() {
            addCriterion("isAutoApprove is null");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveIsNotNull() {
            addCriterion("isAutoApprove is not null");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveEqualTo(Boolean value) {
            addCriterion("isAutoApprove =", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveNotEqualTo(Boolean value) {
            addCriterion("isAutoApprove <>", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveGreaterThan(Boolean value) {
            addCriterion("isAutoApprove >", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isAutoApprove >=", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveLessThan(Boolean value) {
            addCriterion("isAutoApprove <", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveLessThanOrEqualTo(Boolean value) {
            addCriterion("isAutoApprove <=", value, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveIn(List<Boolean> values) {
            addCriterion("isAutoApprove in", values, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveNotIn(List<Boolean> values) {
            addCriterion("isAutoApprove not in", values, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveBetween(Boolean value1, Boolean value2) {
            addCriterion("isAutoApprove between", value1, value2, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andIsautoapproveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isAutoApprove not between", value1, value2, "isautoapprove");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsIsNull() {
            addCriterion("accessTokenValiditySeconds is null");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsIsNotNull() {
            addCriterion("accessTokenValiditySeconds is not null");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsEqualTo(Integer value) {
            addCriterion("accessTokenValiditySeconds =", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsNotEqualTo(Integer value) {
            addCriterion("accessTokenValiditySeconds <>", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsGreaterThan(Integer value) {
            addCriterion("accessTokenValiditySeconds >", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsGreaterThanOrEqualTo(Integer value) {
            addCriterion("accessTokenValiditySeconds >=", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsLessThan(Integer value) {
            addCriterion("accessTokenValiditySeconds <", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsLessThanOrEqualTo(Integer value) {
            addCriterion("accessTokenValiditySeconds <=", value, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsIn(List<Integer> values) {
            addCriterion("accessTokenValiditySeconds in", values, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsNotIn(List<Integer> values) {
            addCriterion("accessTokenValiditySeconds not in", values, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsBetween(Integer value1, Integer value2) {
            addCriterion("accessTokenValiditySeconds between", value1, value2, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andAccesstokenvaliditysecondsNotBetween(Integer value1, Integer value2) {
            addCriterion("accessTokenValiditySeconds not between", value1, value2, "accesstokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsIsNull() {
            addCriterion("refreshTokenValiditySeconds is null");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsIsNotNull() {
            addCriterion("refreshTokenValiditySeconds is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsEqualTo(Integer value) {
            addCriterion("refreshTokenValiditySeconds =", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsNotEqualTo(Integer value) {
            addCriterion("refreshTokenValiditySeconds <>", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsGreaterThan(Integer value) {
            addCriterion("refreshTokenValiditySeconds >", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsGreaterThanOrEqualTo(Integer value) {
            addCriterion("refreshTokenValiditySeconds >=", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsLessThan(Integer value) {
            addCriterion("refreshTokenValiditySeconds <", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsLessThanOrEqualTo(Integer value) {
            addCriterion("refreshTokenValiditySeconds <=", value, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsIn(List<Integer> values) {
            addCriterion("refreshTokenValiditySeconds in", values, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsNotIn(List<Integer> values) {
            addCriterion("refreshTokenValiditySeconds not in", values, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsBetween(Integer value1, Integer value2) {
            addCriterion("refreshTokenValiditySeconds between", value1, value2, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }

        public Criteria andRefreshtokenvaliditysecondsNotBetween(Integer value1, Integer value2) {
            addCriterion("refreshTokenValiditySeconds not between", value1, value2, "refreshtokenvalidityseconds");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_client
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hqj_client
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}